// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ-XNd-z7MPda-jMLk38V6Nu1jbjcptbI',
    appId: '1:837220880208:web:e5a7c5553094b536766655',
    messagingSenderId: '837220880208',
    projectId: 'employee-management-83c78',
    authDomain: 'employee-management-83c78.firebaseapp.com',
    storageBucket: 'employee-management-83c78.firebasestorage.app',
    measurementId: 'G-QXHDZN4N6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcnLehZqOylhimwmzK-J3OSk4930jFoBA',
    appId: '1:837220880208:android:472aa213a95e2267766655',
    messagingSenderId: '837220880208',
    projectId: 'employee-management-83c78',
    storageBucket: 'employee-management-83c78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXHETKqpUAdd5OxWuCLQjqHe7ol6qIxhw',
    appId: '1:837220880208:ios:c5a8fd767be22203766655',
    messagingSenderId: '837220880208',
    projectId: 'employee-management-83c78',
    storageBucket: 'employee-management-83c78.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXHETKqpUAdd5OxWuCLQjqHe7ol6qIxhw',
    appId: '1:837220880208:ios:c5a8fd767be22203766655',
    messagingSenderId: '837220880208',
    projectId: 'employee-management-83c78',
    storageBucket: 'employee-management-83c78.firebasestorage.app',
    iosBundleId: 'com.example.employeeManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ-XNd-z7MPda-jMLk38V6Nu1jbjcptbI',
    appId: '1:837220880208:web:a8b062c20de07405766655',
    messagingSenderId: '837220880208',
    projectId: 'employee-management-83c78',
    authDomain: 'employee-management-83c78.firebaseapp.com',
    storageBucket: 'employee-management-83c78.firebasestorage.app',
    measurementId: 'G-Z7FSQ0CW1N',
  );
}
